version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: linkycat-postgres
    environment:
      POSTGRES_DB: linkycat
      POSTGRES_USER: lcuser
      POSTGRES_PASSWORD: 123
    ports:
      - "3001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
