spring.application.name=linky_cat_api

server.port=1001

spring.datasource.url=jdbc:postgresql://localhost:3001/linkycat
spring.datasource.username=lcuser
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true