spring.application.name=linky_cat_api

server.port=1001

spring.datasource.url=jdbc:postgresql://localhost:3001/linkycat
spring.datasource.username=lcuser
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=your-256-bit-secret-key-here-make-it-long-and-secure-minimum-32-chars
jwt.expiration=1800
jwt.issuer=linky_cat_api